export const labels = {
  appName: 'Takar',
  storeName: 'Latteva',
  dashboard: 'Dashboard',
  sales: 'Penjualan',
  ingredients: 'Bahan',
  reports: 'Laporan',
  more: 'Lainnya',
  settings: 'Pengaturan',
  menus: 'Menu',
  recipes: 'Resep',
  restock: 'Restock',
  waste: 'Waste',
  stockCount: 'Stok Opname',
  todaySales: 'Penjualan hari ini',
  grossProfit: 'Untung kotor',
  sold: 'Terjual',
  lowStock: 'Bahan menipis',
  allStockSafe: 'Semua stok aman',
  quickSale: '+ Penjualan Cepat',
  backupReminder: 'Data tersimpan di browser. Download backup secara rutin.',
  exportData: 'Download backup',
  total: 'Total',
  saveSale: 'Simpan Penjualan',
  emptyCart: 'Keranjang masih kosong · tap + pada menu',
  recipeMissing: 'resep belum dibuat',
  stockWarning: 'Stok bahan kurang. Tetap simpan? Stok akan minus.',
  notEnoughStock: 'tidak cukup.',
  keepSave: 'Tetap simpan',
  cancel: 'Batal',
  saleSaved: 'Penjualan tersimpan',
  recipeMissingConfirm: 'Resep belum dibuat. Tetap tambahkan menu ini?',
  ingredientsTitle: 'Bahan Baku',
  addIngredient: '+ Tambah',
  searchIngredient: 'Cari bahan...',
  all: 'Semua',
  coffee: 'Kopi',
  dairy: 'Dairy',
  packaging: 'Kemasan',
  food: 'Makanan',
  edit: 'Edit',
  editIngredient: 'Edit bahan',
  editMenu: 'Edit menu',
  editCategory: 'Edit kategori',
  confirmDelete: 'Konfirmasi hapus',
  deleteWarning: 'Data yang dihapus tidak bisa dikembalikan.',
  deleteIngredientConfirm: 'Hapus bahan ini?',
  deleteMenuConfirm: 'Hapus menu ini?',
  deleteCategoryConfirm: 'Hapus kategori ini?',
  yesDelete: 'Ya, hapus',
  emptyIngredients: 'Belum ada bahan',
  ingredientNotFound: 'Bahan tidak ditemukan',
  addNewIngredientHint: 'Coba kata kunci lain atau tambah bahan baru.',
  restockQtyPrompt: 'Jumlah restock',
  restockPricePrompt: 'Total harga beli',
  restockSaved: 'Restock tersimpan',
  safe: 'Aman',
  low: 'Menipis',
  empty: 'Habis',
  minus: 'Minus',
  moreTitle: 'Alat usaha',
  moreSubtitle: 'Kelola data dan aktivitas yang tidak dipakai setiap transaksi.',
  menusDescription: 'Tambah, ubah, atau nonaktifkan menu jualan.',
  categoriesDescription: 'Atur pilihan kategori untuk bahan dan menu.',
  recipesDescription: 'Atur bahan dan takaran untuk hitung modal per porsi.',
  restockDescription: 'Catat bahan masuk dan update harga rata-rata.',
  wasteDescription: 'Catat bahan terbuang atau menu gagal produksi.',
  stockCountDescription: 'Samakan stok sistem dengan stok fisik.',
  settingsDescription: 'Backup, pulihkan data, dan atur nama toko.',
  menuList: 'Daftar Menu',
  addMenu: 'Tambah Menu',
  menuName: 'Nama menu',
  category: 'Kategori',
  categoriesTitle: 'Kategori',
  ingredientCategories: 'Kategori bahan',
  menuCategories: 'Kategori menu',
  categoryName: 'Nama kategori',
  addCategory: 'Tambah kategori',
  restoreDefaultCategories: 'Pulihkan kategori default',
  defaultCategoriesRestored: 'Kategori default dipulihkan',
  categoryInUse: 'Kategori masih dipakai, ubah data terkait dulu.',
  categoryDuplicate: 'Kategori dengan nama itu sudah ada.',
  categoryDeleted: 'Kategori dihapus. Data terkait dipindahkan ke',
  sellingPrice: 'Harga jual',
  save: 'Simpan',
  delete: 'Hapus',
  deactivate: 'Nonaktifkan',
  active: 'Aktif',
  inactive: 'Nonaktif',
  chooseMenu: 'Pilih menu',
  chooseIngredient: 'Pilih bahan',
  qty: 'Jumlah',
  unit: 'Satuan',
  hpp: 'Modal per porsi',
  totalHpp: 'Total modal',
  averageHpp: 'Modal rata-rata',
  profit: 'Untung',
  margin: 'Margin',
  recipeRows: 'Bahan resep',
  addRecipeRow: 'Tambah bahan',
  saveRecipe: 'Simpan Resep',
  recipeSaved: 'Resep tersimpan',
  recipeEmptyHint: 'Belum ada bahan. Tap "Tambah bahan" untuk mulai.',
  recipeSavedNext: 'Resep tersimpan ✓ Mau lanjut ke mana?',
  backToMenu: 'Kembali ke Menu',
  goToSales: 'Catat Penjualan',
  restockTitle: 'Restock Bahan',
  purchaseTotalPrice: 'Total harga beli',
  note: 'Catatan',
  wasteTitle: 'Catat Waste',
  wasteModeIngredient: 'Waste bahan',
  wasteModeMenu: 'Waste menu',
  estimatedLoss: 'Estimasi rugi',
  wasteSaved: 'Waste tersimpan',
  stockCountTitle: 'Stok Opname',
  systemStock: 'Stok sistem',
  actualStock: 'Stok fisik',
  difference: 'Selisih',
  stockCountSaved: 'Stok opname tersimpan',
  reportTitle: 'Laporan',
  salesReport: 'Ringkasan penjualan',
  movementAudit: 'Riwayat stok',
  stockOut: 'Stok keluar',
  stockIn: 'Stok masuk',
  stockAdjust: 'Koreksi stok',
  stockBeforeAfter: 'Stok',
  negativeStockNote: 'stok minus',
  noData: 'Belum ada data',
  recipeNeedsMenuAndIngredient: 'Buat menu dan bahan terlebih dahulu sebelum menyusun resep.',
  settingsTitle: 'Pengaturan',
  storeNameLabel: 'Nama toko',
  currency: 'Mata uang',
  lowStockAlert: 'Peringatan stok menipis',
  backupTitle: 'Backup data',
  backupDescription: 'Simpan salinan data ke perangkat. File ini bisa dipakai untuk memulihkan data nanti.',
  restoreTitle: 'Pulihkan data',
  restoreDescription: 'Gunakan file backup JSON dari Takar. Data saat ini akan diganti dengan isi file backup.',
  sampleDataTitle: 'Data contoh',
  sampleDataDescription: 'Isi aplikasi dengan contoh data Latteva untuk mencoba fitur. Jangan gunakan kalau ingin mulai benar-benar kosong.',
  loadSampleData: 'Isi data contoh Latteva',
  sampleDataLoaded: 'Data contoh Latteva berhasil diisi',
  importData: 'Pulihkan dari backup',
  backupOverwriteWarning: 'Import akan menimpa semua data saat ini. Lanjutkan?',
  exportSuccess: 'File backup berhasil dibuat',
  importSuccess: 'Data berhasil diimport',
  chooseFile: 'Pilih file backup JSON',
  menuDeleted: 'Menu dihapus',
  menuDeactivated: 'Menu dinonaktifkan karena sudah punya transaksi',
  ingredientDeleted: 'Bahan dihapus',
  ingredientUsedWarning: 'Bahan masih dipakai di resep. Hapus dari resep dulu.',
  ingredientName: 'Nama bahan',
  currentStock: 'Stok saat ini',
  currentStockHint: 'Jumlah bahan yang ada sekarang',
  initialStock: 'Stok awal',
  initialStockHint: 'Jumlah yang kamu beli pertama kali',
  purchaseTotalPrice: 'Total harga beli',
  purchaseTotalPriceHint: 'Harga total untuk jumlah di atas (app hitung harga per satuannya)',
  minStock: 'Stok minimum',
  avgCostPerUnit: 'Harga rata-rata per unit',
  purchaseCostPerUnit: 'Harga beli per',
  avgCostPerUnitShort: 'Modal rata-rata per',
  avgCostAutoNote: 'Dihitung otomatis dari riwayat Restock. Untuk mengubah, lakukan Restock.',
  initialDataSaved: 'Data tersimpan',
  reset: 'Reset',
  back: 'Kembali',
  saveFailed: 'Gagal menyimpan',
  restoreFailed: 'Gagal memulihkan kategori',
};
